FROM centos:7
  ADD ./bitrix.repo /etc/yum.repos.d/bitrix.repo
  RUN yum -y update
  RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
  RUN yum -y install gcc-c++ make 
  RUN yum -y install nodejs
  RUN yum -y install bx-push-server