FROM centos:7
  ADD ./bitrix.repo /etc/yum.repos.d/bitrix.repo
  ADD ./push-server-multi /etc/sysconfig/push-server-multi
  ADD ./redis.conf /etc/redis.conf
  ADD ./custom.conf /etc/systemd/system/redis.service.d/custom.conf
  RUN yum -y update
  RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
  RUN yum install -y gcc-c++ make 
  RUN yum install -y nodejs mc sudo
  RUN yum install -y bx-push-server
  RUN /etc/init.d/push-server-multi reset
  ENTRYPOINT [ "/etc/init.d/push-server-multi","start"]
  CMD [ "/usr/bin/redis-server", "/etc/redis.conf", "--daemonize no" ]