FROM centos:7
  ADD ./bitrix.repo /etc/yum.repos.d/bitrix.repo
  ADD ./push-server-multi /etc/sysconfig/push-server-multi
  ADD ./redis.conf /etc/redis.conf
  ADD ./custom.conf /etc/systemd/system/redis.service.d/custom.conf
  RUN yum -y update
  RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
  RUN yum -y install gcc-c++ make 
  RUN yum -y install nodejs
  RUN yum -y install bx-push-server
  ENTRYPOINT [ "/etc/init.d/push-server-multi","start" ]
  CMD [ "/usr/bin/redis-server /etc/redis.conf --daemonize no" ]