version: '3.3'
services:
    mysql:
      image: percona/percona-server:5.7
      container_name: bx-mysql
      hostname: mysql
      healthcheck:
        test: "/usr/bin/mysql --user=root --password=${BX_MYSQL_ROOT_PASS} --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
      networks:
        - bitrix
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${BX_MYSQL_ROOT_PASS}
        MYSQL_DATABASE: ${BX_MYSQL_DB}
        MYSQL_USER: bitrix
        MYSQL_PASSWORD: ${BX_MYSQL_BITRIX_PASS}
      volumes:
        - ./bitrix/mysql:/var/lib/mysql
      command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--skip-character-set-client-handshake', '--sql-mode=']

    web:
      image: romannik/bitrix:bitrix-base-new
      container_name: bx-web
      hostname: bitrix
      ports:
        - 80:80
      networks:
        - bitrix
#          ipv4_address: 172.16.16.4
      depends_on:
        - mysql
      volumes:
        - ./bitrix/www/:/home/bitrix/www/
      entrypoint: "/root/entry-web.sh"

    push:
      image: romannik/bitrix:bitrix-base-new
      #image: bitrix-base-image:new
      container_name: bx-push
      hostname: push
      networks:
        - bitrix
#          ipv4_address: 172.16.16.4
      depends_on:
        - web
      privileged: true
      cap_add:
        - SYS_ADMIN
      security_opt:
        - seccomp:unconfined
      #command: sh -c 'mkdir /opt/push-server/logs;node /opt/push-server/server.js --config /opt/push-server/config/config-docker.json;/etc/init.d/push-server-multi start;/usr/bin/redis-server /etc/redis.conf --daemonize no'
      #command: "/root/entry-push.sh"


networks:
  bitrix:
#    name: bitrix_net
#    ipam:
#      config:
#        - subnet: 172.16.16.0/24

    