FROM romannik/bitrix:bitrix-base-new

  COPY entry-web.sh /root/
  ADD entry-mysql.sh /root/entry-mysql.sh
  ADD entry-push.sh /root/entry-push.sh
  RUN chmod +x /root/entry-web.sh
  RUN chmod +x /root/entry-mysql.sh
  RUN chmod +x /root/entry-push.sh
  ADD rtc-server.conf /etc/nginx/bx/site_enabled/rtc-server.conf
  ADD rtc-im_settings.conf /etc/nginx/bx/settings/rtc-im_settings.conf
  ADD rtc-im_subscrider.conf /etc/nginx/bx/conf/rtc-im_subscrider.conf
  ADD redis.conf /etc/redis/redis.conf
  ADD push-server-multi bitrix-new:/etc/sysconfig/push-server-multi
  RUN /etc/init.d/push-server-multi reset
  RUN mkdir -p /opt/push-server/logs
  RUN yum -y clean all