FROM romannik/bitrix:bitrix-base-new

  COPY entry-web.sh /root/
  COPY entry-mysql.sh /root/
  COPY entry-push.sh /root/
  RUN chmod +x /root/entry-web.sh
  RUN chmod +x /root/entry-mysql.sh
  RUN chmod +x /root/entry-push.sh
  COPY rtc-server.conf /etc/nginx/bx/site_enabled/
  COPY rtc-im_settings.conf /etc/nginx/bx/settings/
  COPY rtc-im_subscrider.conf /etc/nginx/bx/conf/
  COPY redis.conf /etc/redis/
  COPY push-server-multi bitrix-new:/etc/sysconfig/push-server-multi
  RUN /etc/init.d/push-server-multi reset
  RUN mkdir -p /opt/push-server/logs
  RUN yum -y clean all